### ISSUE TITLE
Debounce setUrlHash to prevent history abuse

### ISSUE THREAD

**Issue by Pustur** [9elements/fancy-border-radius#1]
Hi and thanks for this informative tool.

I was playing around with it for a while and then I realized that my history was flooded with entries from your tool. It would be great if the function responsible for adding entries to the history would be debounced.

https://github.com/9elements/fancy-border-radius/blob/232a63cb369bf3150960d95051487e70ff6bd3fe/src/js/adjustable_box.js#L71-L77

**Comment by mirko314** [comment]
Thank you for your suggestion, it was fixed in the last commit:
https://github.com/9elements/fancy-border-radius/commit/206d29dab76d60c4b8d4faec79c701a46927eddc
Now the history just gets written when movement stops.
