### ISSUE TITLE
Web site cannot be opened

### ISSUE THREAD

**Issue by ChenErik** [9elements/fancy-border-radius#13]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/37365363/198598763-8ac0a8dc-a083-4647-b176-5045cd721bc2.png">

**Comment by arjanvillon** [comment]
same here. there seems to be a recent merge on the repo. i just cloned it for now and checkout on the version that's working and run it on my local machine.

**Comment by mirko314** [comment]
Thank you for reporting the outage. We were upgrading the deployment mechanism, now everything should be working fine again.
