### ISSUE TITLE
dist folder in repository

### ISSUE THREAD

**Issue by KonradLinkowski** [9elements/fancy-border-radius#3]
I stumbled upon this cool tool and I thought it would be nice if dist folder would be generated automatically through github actions instead of commiting it everytime you do a change.
Here is the gist a created for that purpose. Can somebody look at this?
https://gist.github.com/KonradLinkowski/4b2b825d2540c4eecfc5dc1f9e42a87f
Probably there are more ways of doing this.

**Comment by mirko314** [comment]
Thank you very much, the snippet looks good. Still, we are currently happy with our deployment.
